#ifndef CONFIG_H
#define CONFIG_H

#define DISPLAY_SPI_CLK_HZ (8 * 1000 * 1000)
#define DEFAULT_BRIGHTNESS 30
#define LOW_BRIGHTNESS 15
#define HIGH_BRIGHTNESS 30
#define BACKLIGHT_PWM_FREQ_HZ 20000
#define BACKLIGHT_PWM_DUTY_RESOLUTION LEDC_TIMER_10_BIT
#define BACKLIGHT_PWM_CLK_CFG LEDC_USE_XTAL_CLK

#endif
